package vpn;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

public class ConnectVPN extends javax.swing.JFrame {

    private static final String CONF_FILE_EXTENSION = "conf";
    private static final String CONF_FILE_DESCRIPTION = "Файлы конфигураций";

    private static final String INPUT_LDAP_NAME = "Введите логин";
    private static final String INPUT_PASS_NAME = "Пароль";
    private static final String INPUT_OTP_NAME = "Введите ОТП";
    private static final String EMPTY_STRING = "";

    private FileFilter confFilter = new ConfFileFilter(CONF_FILE_EXTENSION, CONF_FILE_DESCRIPTION);

    private ConnectData connectData = new ConnectData();

    public ConnectVPN() {
        initComponents();
        initPanel();
        FileChooser.setCurrentDirectory(new File("/etc/openvpn"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SaveData = new javax.swing.JCheckBox();
        FileChooser = new javax.swing.JFileChooser();
        addConfiguration = new javax.swing.JPanel();
        txtAddConfiguration = new javax.swing.JTextField();
        btnAddConfiguration = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        addClientData = new javax.swing.JPanel();
        txtLdapLogin = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtOTP = new javax.swing.JTextField();
        chboxSaveData = new javax.swing.JCheckBox();
        btnConnect = new javax.swing.JButton();

        SaveData.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addConfiguration.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtAddConfiguration.setEditable(false);
        txtAddConfiguration.setText("Address settings");
        txtAddConfiguration.setToolTipText("Адрес к конфигурационному файлу");
        txtAddConfiguration.setActionCommand("<Not Set>");
        txtAddConfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddConfigurationActionPerformed(evt);
            }
        });

        btnAddConfiguration.setText("Add Settings");
        btnAddConfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddConfigurationActionPerformed(evt);
            }
        });

        jLabel1.setText("Connect to OpenVPN");

        javax.swing.GroupLayout addConfigurationLayout = new javax.swing.GroupLayout(addConfiguration);
        addConfiguration.setLayout(addConfigurationLayout);
        addConfigurationLayout.setHorizontalGroup(
            addConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addConfigurationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAddConfiguration, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddConfiguration, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addConfigurationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(121, 121, 121))
        );
        addConfigurationLayout.setVerticalGroup(
            addConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addConfigurationLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddConfiguration)
                    .addComponent(btnAddConfiguration))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        txtLdapLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLdapLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLdapLoginFocusLost(evt);
            }
        });

        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        txtOTP.setToolTipText("Поле для ввода одноразового пароля");
        txtOTP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOTPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOTPFocusLost(evt);
            }
        });

        chboxSaveData.setText("Save connection data  ");
        chboxSaveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chboxSaveDataActionPerformed(evt);
            }
        });

        btnConnect.setText("Connect");

        javax.swing.GroupLayout addClientDataLayout = new javax.swing.GroupLayout(addClientData);
        addClientData.setLayout(addClientDataLayout);
        addClientDataLayout.setHorizontalGroup(
            addClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addClientDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addClientDataLayout.createSequentialGroup()
                        .addGroup(addClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtOTP)
                            .addComponent(txtLdapLogin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPassword)
                            .addComponent(btnConnect, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                        .addGap(11, 11, 11))
                    .addGroup(addClientDataLayout.createSequentialGroup()
                        .addComponent(chboxSaveData)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        addClientDataLayout.setVerticalGroup(
            addClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addClientDataLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(addClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLdapLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConnect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chboxSaveData)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addConfiguration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addClientData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addConfiguration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addClientData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initPanel() {
        txtOTP.setText(INPUT_OTP_NAME);
        txtLdapLogin.setText(INPUT_LDAP_NAME);
        txtPassword.setText(INPUT_PASS_NAME);
    }

    private void txtAddConfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddConfigurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddConfigurationActionPerformed

    private void chboxSaveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chboxSaveDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chboxSaveDataActionPerformed

    private void btnAddConfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddConfigurationActionPerformed
        FileUtils.addFileFilter(FileChooser, confFilter);
        int result = FileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File confFile = FileChooser.getSelectedFile();

            String path = confFile.getPath();
            connectData.setPathConfFile(path);
            txtAddConfiguration.setText(path);
        }
    }//GEN-LAST:event_btnAddConfigurationActionPerformed

    private void txtLdapLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLdapLoginFocusGained
        if (txtLdapLogin.getText().equals(INPUT_LDAP_NAME)) {
            txtLdapLogin.setText(EMPTY_STRING);
        }
    }//GEN-LAST:event_txtLdapLoginFocusGained

    private void txtLdapLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLdapLoginFocusLost
        if (txtLdapLogin.getText().trim().equals(EMPTY_STRING)) {
            txtLdapLogin.setText(INPUT_LDAP_NAME);
        }
    }//GEN-LAST:event_txtLdapLoginFocusLost

    private void txtOTPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOTPFocusGained
        if (txtOTP.getText().equals(INPUT_OTP_NAME)) {
            txtOTP.setText(EMPTY_STRING);
        }
    }//GEN-LAST:event_txtOTPFocusGained

    private void txtOTPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOTPFocusLost
        if (txtOTP.getText().trim().equals(EMPTY_STRING)) {
            txtOTP.setText(INPUT_OTP_NAME);
        }
    }//GEN-LAST:event_txtOTPFocusLost

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        if (txtPassword.getText().equals(INPUT_PASS_NAME)) {
            txtPassword.setText(EMPTY_STRING);
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if (txtPassword.getText().equals(EMPTY_STRING)) {
            txtPassword.setText(INPUT_PASS_NAME);
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConnectVPN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConnectVPN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConnectVPN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConnectVPN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConnectVPN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JCheckBox SaveData;
    private javax.swing.JPanel addClientData;
    private javax.swing.JPanel addConfiguration;
    private javax.swing.JButton btnAddConfiguration;
    private javax.swing.JButton btnConnect;
    private javax.swing.JCheckBox chboxSaveData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtAddConfiguration;
    private javax.swing.JTextField txtLdapLogin;
    private javax.swing.JTextField txtOTP;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
